/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./.rnstorybook/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '58px', fontWeight: '600' }],
        h2: ['40px', { lineHeight: '48px', fontWeight: '600' }],
        h3: ['32px', { lineHeight: '38px', fontWeight: '600' }],
        h4: ['28px', { lineHeight: '34px', fontWeight: '600' }],
        h5: ['24px', { lineHeight: '28px', fontWeight: '600' }],
        s1: ['18px', { lineHeight: '28px', fontWeight: '600' }],
        s2: ['16px', { lineHeight: '24px', fontWeight: '600' }],
        b1: ['16px', { lineHeight: '24px', fontWeight: '400' }],
        b2: ['16px', { lineHeight: '24px', fontWeight: '500' }],
        b3: ['14px', { lineHeight: '20px', fontWeight: '400' }],
        b4: ['14px', { lineHeight: '20px', fontWeight: '500' }],
        c1: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        c2: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        c3: ['10px', { lineHeight: '14px', fontWeight: '500' }],
        label: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'btn-giant':  ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'btn-large':  ['16px', { lineHeight: '20px', fontWeight: '600' }],
        'btn-medium': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'btn-small':  ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'btn-tiny':   ['10px', { lineHeight: '12px', fontWeight: '600' }],
      },
      colors: {
        /* ── Primitive palette ── */
        primary: {
          50:  'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          DEFAULT: 'var(--color-primary-600)',
        },
        grey: {
          50:  'var(--color-grey-50)',
          100: 'var(--color-grey-100)',
          200: 'var(--color-grey-200)',
          300: 'var(--color-grey-300)',
          400: 'var(--color-grey-400)',
          500: 'var(--color-grey-500)',
          600: 'var(--color-grey-600)',
          700: 'var(--color-grey-700)',
          800: 'var(--color-grey-800)',
          900: 'var(--color-grey-900)',
        },
        green: {
          50:  'var(--color-green-50)',
          100: 'var(--color-green-100)',
          200: 'var(--color-green-200)',
          300: 'var(--color-green-300)',
          400: 'var(--color-green-400)',
          500: 'var(--color-green-500)',
          600: 'var(--color-green-600)',
          700: 'var(--color-green-700)',
          800: 'var(--color-green-800)',
          900: 'var(--color-green-900)',
        },
        red: {
          50:  'var(--color-red-50)',
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
        },
        yellow: {
          50:  'var(--color-yellow-50)',
          100: 'var(--color-yellow-100)',
          200: 'var(--color-yellow-200)',
          300: 'var(--color-yellow-300)',
          400: 'var(--color-yellow-400)',
          500: 'var(--color-yellow-500)',
          600: 'var(--color-yellow-600)',
          700: 'var(--color-yellow-700)',
          800: 'var(--color-yellow-800)',
          900: 'var(--color-yellow-900)',
        },
        blue: {
          50:  'var(--color-blue-50)',
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
        },
        /* ── Semantic: Backgrounds ── */
        'bg-default': 'var(--bg-default)',
        'bg-surface':  'var(--bg-surface)',
        'bg-subtle':   'var(--bg-subtle)',
        'bg-muted':    'var(--bg-muted)',
        'bg-inverse':  'var(--bg-inverse)',
        /* ── Semantic: Borders ── */
        'border-default': 'var(--border-default)',
        'border-strong':  'var(--border-strong)',
        'border-subtle':  'var(--border-subtle)',
        'border-brand':   'var(--border-brand)',
        /* ── Semantic: Text ── */
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary':  'var(--text-tertiary)',
        'text-disabled':  'var(--text-disabled)',
        'text-inverse':   'var(--text-inverse)',
        'text-brand':     'var(--text-brand)',
        /* ── Semantic: Actions ── */
        'action-primary':        'var(--action-primary)',
        'action-primary-hover':  'var(--action-primary-hover)',
        'action-primary-active': 'var(--action-primary-active)',
        'action-primary-subtle': 'var(--action-primary-subtle)',
        'action-primary-text':   'var(--action-primary-text)',
        /* ── Semantic: Status ── */
        'status-success':        'var(--status-success)',
        'status-success-subtle': 'var(--status-success-subtle)',
        'status-success-strong': 'var(--status-success-strong)',
        'status-error':          'var(--status-error)',
        'status-error-subtle':   'var(--status-error-subtle)',
        'status-error-strong':   'var(--status-error-strong)',
        'status-warning':        'var(--status-warning)',
        'status-warning-subtle': 'var(--status-warning-subtle)',
        'status-warning-strong': 'var(--status-warning-strong)',
        'status-info':           'var(--status-info)',
        'status-info-subtle':    'var(--status-info-subtle)',
        'status-info-strong':    'var(--status-info-strong)',
        /* ── Legacy aliases (backward-compat) ── */
        secondary: 'var(--color-green-500)',
        error:      'var(--color-red-500)',
        warning:    'var(--color-yellow-500)',
        surface:    'var(--bg-surface)',
        background: 'var(--bg-default)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        xs:   'var(--radius-xs)',
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        100: 'var(--shadow-100)',
        200: 'var(--shadow-200)',
        300: 'var(--shadow-300)',
        400: 'var(--shadow-400)',
        500: 'var(--shadow-500)',
        600: 'var(--shadow-600)',
        700: 'var(--shadow-700)',
        800: 'var(--shadow-800)',
      },
    },
  },
  plugins: [],
};
