export const colors = {
  /* ── Primitive: Primary ── */
  'primary-50':  'var(--color-primary-50)',
  'primary-100': 'var(--color-primary-100)',
  'primary-200': 'var(--color-primary-200)',
  'primary-300': 'var(--color-primary-300)',
  'primary-400': 'var(--color-primary-400)',
  'primary-500': 'var(--color-primary-500)',
  'primary-600': 'var(--color-primary-600)',
  'primary-700': 'var(--color-primary-700)',
  'primary-800': 'var(--color-primary-800)',
  'primary-900': 'var(--color-primary-900)',
  /* ── Primitive: Grey ── */
  'grey-50':  'var(--color-grey-50)',
  'grey-100': 'var(--color-grey-100)',
  'grey-200': 'var(--color-grey-200)',
  'grey-300': 'var(--color-grey-300)',
  'grey-400': 'var(--color-grey-400)',
  'grey-500': 'var(--color-grey-500)',
  'grey-600': 'var(--color-grey-600)',
  'grey-700': 'var(--color-grey-700)',
  'grey-800': 'var(--color-grey-800)',
  'grey-900': 'var(--color-grey-900)',
  /* ── Primitive: Green ── */
  'green-50':  'var(--color-green-50)',
  'green-100': 'var(--color-green-100)',
  'green-200': 'var(--color-green-200)',
  'green-300': 'var(--color-green-300)',
  'green-400': 'var(--color-green-400)',
  'green-500': 'var(--color-green-500)',
  'green-600': 'var(--color-green-600)',
  'green-700': 'var(--color-green-700)',
  'green-800': 'var(--color-green-800)',
  'green-900': 'var(--color-green-900)',
  /* ── Primitive: Red ── */
  'red-50':  'var(--color-red-50)',
  'red-100': 'var(--color-red-100)',
  'red-200': 'var(--color-red-200)',
  'red-300': 'var(--color-red-300)',
  'red-400': 'var(--color-red-400)',
  'red-500': 'var(--color-red-500)',
  'red-600': 'var(--color-red-600)',
  'red-700': 'var(--color-red-700)',
  'red-800': 'var(--color-red-800)',
  'red-900': 'var(--color-red-900)',
  /* ── Primitive: Yellow ── */
  'yellow-50':  'var(--color-yellow-50)',
  'yellow-100': 'var(--color-yellow-100)',
  'yellow-200': 'var(--color-yellow-200)',
  'yellow-300': 'var(--color-yellow-300)',
  'yellow-400': 'var(--color-yellow-400)',
  'yellow-500': 'var(--color-yellow-500)',
  'yellow-600': 'var(--color-yellow-600)',
  'yellow-700': 'var(--color-yellow-700)',
  'yellow-800': 'var(--color-yellow-800)',
  'yellow-900': 'var(--color-yellow-900)',
  /* ── Primitive: Blue ── */
  'blue-50':  'var(--color-blue-50)',
  'blue-100': 'var(--color-blue-100)',
  'blue-200': 'var(--color-blue-200)',
  'blue-300': 'var(--color-blue-300)',
  'blue-400': 'var(--color-blue-400)',
  'blue-500': 'var(--color-blue-500)',
  'blue-600': 'var(--color-blue-600)',
  'blue-700': 'var(--color-blue-700)',
  'blue-800': 'var(--color-blue-800)',
  'blue-900': 'var(--color-blue-900)',
  /* ── Semantic: Backgrounds ── */
  'bg-default': 'var(--bg-default)',
  'bg-surface':  'var(--bg-surface)',
  'bg-subtle':   'var(--bg-subtle)',
  'bg-muted':    'var(--bg-muted)',
  'bg-inverse':  'var(--bg-inverse)',
  /* ── Semantic: Text ── */
  'text-primary':   'var(--text-primary)',
  'text-secondary': 'var(--text-secondary)',
  'text-tertiary':  'var(--text-tertiary)',
  'text-disabled':  'var(--text-disabled)',
  'text-inverse':   'var(--text-inverse)',
  'text-brand':     'var(--text-brand)',
  /* ── Semantic: Actions ── */
  'action-primary':        'var(--action-primary)',
  'action-primary-hover':  'var(--action-primary-hover)',
  'action-primary-active': 'var(--action-primary-active)',
  'action-primary-subtle': 'var(--action-primary-subtle)',
  /* ── Semantic: Status ── */
  'status-success':        'var(--status-success)',
  'status-success-subtle': 'var(--status-success-subtle)',
  'status-success-strong': 'var(--status-success-strong)',
  'status-error':          'var(--status-error)',
  'status-error-subtle':   'var(--status-error-subtle)',
  'status-error-strong':   'var(--status-error-strong)',
  'status-warning':        'var(--status-warning)',
  'status-warning-subtle': 'var(--status-warning-subtle)',
  'status-warning-strong': 'var(--status-warning-strong)',
  'status-info':           'var(--status-info)',
  'status-info-subtle':    'var(--status-info-subtle)',
  'status-info-strong':    'var(--status-info-strong)',
} as const;

export const spacing = {
  xs:   4,
  sm:   8,
  3:    12,
  md:   16,
  5:    20,
  lg:   24,
  xl:   32,
  10:   40,
  xxl:  48,
  16:   64,
  20:   80,
} as const;

export const borderRadius = {
  none: 'var(--radius-none)',
  xs:   'var(--radius-xs)',
  sm:   'var(--radius-sm)',
  md:   'var(--radius-md)',
  lg:   'var(--radius-lg)',
  xl:   'var(--radius-xl)',
  full: 'var(--radius-full)',
} as const;

export const shadows = {
  100: 'var(--shadow-100)',
  200: 'var(--shadow-200)',
  300: 'var(--shadow-300)',
  400: 'var(--shadow-400)',
  500: 'var(--shadow-500)',
  600: 'var(--shadow-600)',
  700: 'var(--shadow-700)',
  800: 'var(--shadow-800)',
} as const;

// Raw hex values for React Native prop contexts (e.g. placeholderTextColor, tintColor)
// where CSS variables are not supported. Keep in sync with styles/tokens.css.
export const primitiveColors = {
  white: '#FFFFFF',
  'grey-50':  '#F9FAFB',
  'grey-100': '#F3F4F6',
  'grey-200': '#E5E7EA',
  'grey-300': '#D2D5DB',
  'grey-400': '#9EA2AE',
  'grey-500': '#6D717F',
  'grey-600': '#4D5461',
  'grey-700': '#394050',
  'grey-800': '#212936',
  'grey-900': '#131927',
  'primary-50':  '#EDEFFE',
  'primary-100': '#C8CEFC',
  'primary-200': '#AEB6FB',
  'primary-500': '#4E61F6',
  'primary-600': '#4758E0',
  'green-50':  '#ECF8EF',
  'green-500': '#43B75D',
  'red-50':    '#FDECEC',
  'red-500':   '#EE443F',
  'yellow-50':  '#FFF7E6',
  'yellow-500': '#FFAA00',
  'blue-50':   '#E6F4FF',
  'blue-500':  '#0095FF',
} as const;

export type ColorToken = keyof typeof colors;
export type SpacingToken = keyof typeof spacing;
export type RadiusToken = keyof typeof borderRadius;
export type ShadowToken = keyof typeof shadows;
export type PrimitiveColorToken = keyof typeof primitiveColors;
